-- --------------------------------------------------------------
-- BASE DE DATOS: Importadora GonSeg
-- PLATAFORMA: Supabase (PostgreSQL)
-- FECHA DE EXTRACCIÓN: 24/11/2024
-- --------------------------------------------------------------

-- 1. TIPOS DE DATOS PERSONALIZADOS (ENUMS)
-- Se detectó el uso de un tipo 'user_role' en la tabla users
CREATE TYPE public.user_role AS ENUM ('admin', 'importador', 'client', 'usuario');

-- --------------------------------------------------------------
-- 2. DEFINICIÓN DE TABLAS
-- --------------------------------------------------------------

-- TABLA: USERS
-- Gestión de usuarios, clientes y administradores
CREATE TABLE public.users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email text NOT NULL,
    password text NOT NULL,
    full_name text NOT NULL,
    role public.user_role DEFAULT 'client'::public.user_role,
    address text,
    phone text,
    company_name text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- TABLA: PRODUCTS
-- Catálogo general de productos
CREATE TABLE public.products (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    description text,
    price numeric NOT NULL,
    image text,
    category text,
    stock integer DEFAULT 0,
    featured boolean DEFAULT false,
    provider_id bigint REFERENCES public.users(id), -- Vinculado a quien lo importó
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- TABLA: ORDERS
-- Cabecera de los pedidos realizados
CREATE TABLE public.orders (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint REFERENCES public.users(id),
    total_amount numeric NOT NULL,
    status text DEFAULT 'pendiente',
    shipping_address text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- TABLA: ORDER_ITEMS
-- Detalle de productos por cada pedido
CREATE TABLE public.order_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id bigint REFERENCES public.orders(id),
    product_id bigint REFERENCES public.products(id),
    quantity integer NOT NULL,
    unit_price numeric NOT NULL,
    subtotal numeric
);

-- --------------------------------------------------------------
-- 3. CONFIGURACIÓN DE SEGURIDAD (RLS)
-- --------------------------------------------------------------

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;

-- Fin del esquema